### ISSUE TITLE
Following up the Switch issue

### ISSUE THREAD

**Issue by Ackons** [Oreo639/LimePlayer3DS#1]
Hi, I'm sorry for contacting you here, but I don't think there's a way to "message" people on github. I put hbl.nsp in my atmosphere folder on the SD card (I couldn't find an hbloader.nro to put on my root though) and when I go into the album now I get error code 2168-0000 (0xa8). Do you know any fixes for this? Sorry if I am wasting your time at all.

**Comment by Oreo639** [comment]
https://github.com/switchbrew/nx-hbmenu/releases
My bad, I meant hbmenu.nro
