### ISSUE TITLE
Error 1002 on loading pls and m3u files

### ISSUE THREAD

**Issue by INFINITE-PIKA** [Oreo639/LimePlayer3DS#13]
I'm using 0.0.0-31da8bc, and when I try to play some internet radio files, I get this error:
Error code 1002
Failed to initialize decoder
How can I fix this? I assume this is my bad

**Comment by Oreo639** [comment]
Can you share the pls/m3u file?

**Comment by INFINITE-PIKA** [comment]
[https://drive.google.com/drive/folders/1SINpfH1o-TjbDqRDSMSfAsns7-4onXpN?usp=sharing](url)

**Comment by Oreo639** [comment]
Playlist files pointing to other playlist files isn't supported rn. You would have to use the playlist file. 
For j-rock, you would have to download [http://51.81.46.118:3340/listen.pls?sid=1](http://51.81.46.118:3340/listen.pls?sid=1), rename it, then put it on your sd card.

**Comment by INFINITE-PIKA** [comment]
Got it, thanks a ton
