### ISSUE TITLE
[Feature Request] More support for special characters

### ISSUE THREAD

**Issue by CSab6482** [oreo639/LimePlayer3DS#18]
I have a `.pls` file that contains the following lines
```json
File5=sdmc:/music/Hawái - Single/01 Hawái.mp3
Title5=Hawái
Length5=200
```
When my playlist gets to this song, I get the following error, and the song is skipped.
![mrg_2022-05-23_18-15-24 951](https://user-images.githubusercontent.com/53708281/169914482-8ea32cab-2fec-4c42-aa0e-7166d741ef47.jpg)

~I haven't been able to get any of my `.m3u` files to work, so I'm not sure if that is a feature that has been implemented or not. For reference, I created my `.m3u` files with VLC.~
`.m3u` files created with [Clementine](https://www.clementine-player.org/) work fine.

**Comment by oreo639** [comment]
Are you running this on real hardware? It seems to work fine for me there, although there is some funky behavior on Citra.

**Comment by CSab6482** [comment]
Yes, this is on a 2DS XL running 11.15.0

**Comment by oreo639** [comment]
Sorry, I can't reproduce this on hardware with a file of the same filepath.

**Comment by CSab6482** [comment]
Maybe it's something else in the file then? This is the data that Mp3tag shows me.
![image](https://user-images.githubusercontent.com/53708281/169921733-2fe7890f-dc4f-4b53-8ce6-99a6da190955.png)

**Comment by oreo639** [comment]
How does the filename appear when you navigate to it in the file browser?

**Comment by CSab6482** [comment]
I'm not sure what you mean. Does this image of the file in File Explorer help?
![image](https://user-images.githubusercontent.com/53708281/169922785-c98f2d45-2654-4fed-b3b7-4c983a3d47c2.png)

**Comment by oreo639** [comment]
No, I mean in limeplayer.

**Comment by CSab6482** [comment]
Oh, I've since renamed the file and metadata with a normal a, but it was the `sdmc:/music/Hawái - Single/01 Hawái.mp3` directory from earlier.

**Comment by oreo639** [comment]
Well, regardless, if you want, you can still share a relevant log with the error in `sdmc:/3ds/limeplayer3ds/` (the last 4 are kept, keep in mind this will contain song filenames)

**Comment by CSab6482** [comment]
Interestingly enough, I added the original `Hawái - Single/01 Hawái.mp3` folder/song, and it doesn't show up in the file browser for LimePlayer3DS

**Comment by oreo639** [comment]
> and it doesn't show up in the file browser for LimePlayer3DS

No question marks or anything?

**Comment by CSab6482** [comment]
> No question marks or anything? (just double checking)

I figured out why it wouldn't show up. On my 2DS XL I had a folder called `Hawái - Single`, and I added a folder named `Hawái - Single`. On my 2DS XL, the contents of the `Hawái - Single` folder simply merged into the `Hawai - Single` one. After deleting the `Hawai - Single` folder, I could successfully keep the new `Hawái - Single` one.
![mrg_2022-05-23_20-14-36 271](https://user-images.githubusercontent.com/53708281/169924494-4bfeb88b-16df-4a35-8161-b4974a4d6f32.jpg)

**Comment by oreo639** [comment]
I assume the pls works fine now?

**Comment by CSab6482** [comment]
![mrg_2022-05-23_21-19-57 191](https://user-images.githubusercontent.com/53708281/169929436-b1cdfec2-9a30-46d3-899d-ca1d2b22ffa8.jpg)
It's still the same issue unfortunately. The `01 Hawai.mp3` version works fine though.

**Comment by oreo639** [comment]
Alright, can you go to `sdmc:/3ds/limeplayer3ds/0.log` and open it in something like notepad++?
Inside you should see a line saying something like `[/home/oreo639/git/my-projects/LimePlayer3DS/src/file.cpp] <number>: Could not open <filename here>`, is that filename garbled in any way.

My guess is that the pls file is not UTF-8 where as the file name is UTF-8, so LimePlayer can't open the file. (You can convert the pls file to UTF-8 using notepad++ and setting it in the encoding tab: https://stackoverflow.com/a/8432691)

**Comment by CSab6482** [comment]
I see this
```json
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 307: Playback complete.
[/home/oreo639/git/gitall/LimePlayer3DS/src/file.cpp] 35: Extension: mp3
[/home/oreo639/git/gitall/LimePlayer3DS/src/file.cpp] 38: Could not open sdmc:/music/Hawái - Single/01 Hawái.mp3. Please make sure file exists.
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 384: Using stdio transport.
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 248: Failed to open transport.
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 311: Decoder could not be initalized.
[/home/oreo639/git/gitall/LimePlayer3DS/src/file.cpp] 35: Extension: mp3
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 384: Using stdio transport.
[/home/oreo639/git/gitall/LimePlayer3DS/src/player.cpp] 341: Attempting to load the Mp3 decoder.
[/home/oreo639/git/gitall/LimePlayer3DS/src/gui/gui.cpp] 71: Gui is exiting.
```
You were right about the UTF-8 problem. The `.pls` file was ANSI, and saving is as UTF-8 fixed the problem. Thank you so much for all your help in debugging this!

**Comment by oreo639** [comment]
Alright. Sorry for the confusion. Glad it's resolved now.
